spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB:popcorn_palace}
    username: ${POSTGRES_USER:admin}
    password: ${POSTGRES_PASSWORD:admin}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
  flyway:
    enabled: true

server:
  port: ${APP_PORT:10001}

management:
  endpoints:
    web:
      exposure:
        include: health,info