spring:
  datasource:
    url: jdbc:postgresql://db:5432/popcorn_palace
    username: postgres
    password: password123
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
  flyway:
    enabled: true

server:
  port: 10001

management:
  endpoints:
    web:
      exposure:
        include: health,info